const Dishes = [
    //Make Ur Momo
    { name: "Deep Fried Momo", price: 10, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Tandoori Momo", price: 30, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Kurkure Momo", price: 40, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Pan Fried Momo (Chilly)", price: 50, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Lollipop Momo", price: 50, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Manchurian Momo", price: 50, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Pizza Topping Momo", price: 50, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Volcanic Momo", price: 40, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Jhol Momo", price: 40, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Crispy Bottom Momo", price: 20, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Cheese Overload Momo", price: 80, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    { name: "Crystal Clear Momo", price: 60, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Make Your Momo" },
    //Momos
    { name: "Veggie Momos", price: 59, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Veggie Cheese Momos", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Super Corn Cheese", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Paneer Momos", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Paneer Cheese Momos", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Momos"},
    { name: "Mushroom Momos", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Soya Keema Momos", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Butter Paneer Momo", price: 139, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Momos" },
    { name: "Traditional Chicken Momos", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    { name: "Chicken Cheese Momos", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    { name: "Mutton Keema Momos", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    { name: "Fish Momos", price: 139, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    { name: "Prawn Momos", price: 159, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    { name: "Butter Chicken Momo", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Momos" },
    // { name: "Choice of Dough", price: "Tandoor Flavour", image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600" },
    // { name: "Wheat", price: 15, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600" },
    // { name: "Achari", price: "We use 100% Vegetable oil", image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600" },
    // { name: "Afghani Malai Pahadi", price: 29, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600" }, 
    //Chinese
    { name: "Chilly Paneer", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Mushroom Chilly", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Veg Manchurian", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Chilly Potato", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Honey Chilly Potato", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Veg Noodles", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Hakka Noodles", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Singapore Noodles", price: 139, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "American Chopsey", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Crispy Corn", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Chineese"},
    { name: "Chilly Chicken", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Dragon Chicken", price: "Veg Cheese Nuggets", image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Chicken Manchurian", price: 189, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Prawn Chilly", price: 329, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Crispy Golden Prawn", price: 329, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Chicken Noodles", price: 159, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Chicken Singapore Noodles", price: 179, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Mutton Noodles", price: 189, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Chineese"},
    { name: "Chicken Chopsey", price: 159, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type: "Chineese" },
    // Rolls
    { name: "Veg Roll", price: 69, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Paneer Roll", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Paneer Schezwan Roll", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Paneer Chowmein Roll", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Special Paneer Roll", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Chowmein Roll", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Veg Manchurian Roll", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Veg Spring Roll", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Rolls"},
    { name: "Egg Roll", price: 69, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Chicken Roll", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Chicken Schezwan Roll", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Special Chicken Roll", price: 129, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Chicken Chowmein Roll", price: 119, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Chicken Bhuma Roll", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Chicken Spring Roll", price: 159, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Mutton Roll", price: 169, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Rolls"},
    { name: "Mutton Chowmein Roll", price: 169, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type: "Rolls" },
    // Burgers
    { name: "Mo'Aloo Tikki Burger", price: 49, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Burgers"},
    { name: "Mo'Paneer Burger", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Burgers"},
    { name: "Mo'Chicken Burger", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Burgers"},
    // { name: "Add On Cheese", price: 20, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600" },
    // Sides
    { name: "French Fries", price: 69, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Peri Peri French Fries", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Cheese Overload Fries", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Veg Nuggets", price: 69, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Veg Cheese Nuggets", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Paneer Veg Pocket", price: 69, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Sides"},
    { name: "Chicken Nuggets", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type:"Sides"},
    { name: "Chicken Pocket", price: 79, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type:"Sides"},
    { name: "Chicken Popcorn", price: 139, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type:"Sides"},
    { name: "Chicken Boneless Strips", price: 159, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type:"Sides" },
    // Mo Freezer
    { name: "Fresh Mint Freezer", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Exotic Peach Freezer", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "The Three Musketeers [Strawberry, Raspberry, Blueberry]", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Strawberry Freezer", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Beverages" },
    { name: "Tangy Mango Freezer", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Blueberry Freezer", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Bubblegum Freezer", price: 120, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Iconic Fruit Beer", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    // Mo Ice Tea
    { name: "Classic Lemon Ice Tea", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Exotic Peach Ice Tea", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "The Three Musketeers", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Strawberry Ice Tea", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Tangy Mango Ice Tea", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Blueberry Ice Tea", price: 110, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Bubblegum Ice Tea", price: 120, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    // Coffee
    { name: "Cold Coffee", price: 60, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Irish Cold Coffee", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    { name: "Hazel Nut Cold Coffee", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Beverages"},
    // Mo Shakes
    { name: "Strawberry Shake", price: 80, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Tropical Mango Shake", price: 80, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Beverages" },
    { name: "Blueberry Shake", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Very Berry Shake", price: 90, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Bubblegum Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Oreo Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Oreo Kitkat Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Cookies And Cream Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Original Vanilla Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Hazel Nut Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Choco Irish Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    { name: "Nutella Shake", price: 100, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type:"Beverages"},
    // Ramen
    { name: "Veg Ramen", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg" , type: "Ramen"},
    { name: "Chicken Ramen", price: 129, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg", type: "Ramen" },
    { name: "Mutton Ramen", price: 149, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type: "Ramen"},
    // Soup
    { name: "Veg Man-Chow Soup", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Soup" },
    { name: "Veg Hot & Sour Soup", price: 89, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Soup" },
    { name: "Mushroom Soup", price: 99, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Veg", type:"Soup" },
    { name: "Chicken Man-Chow Soup", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type:"Soup"},
    { name: "Chicken Hot & Sour Soup", price: 109, image: "https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Non-Veg" , type:"Soup"},
];
export default Dishes;